# Generated by Django 3.2.8 on 2021-10-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbank_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='open_date',
            field=models.DateField(auto_now=True),
        ),
    ]
