# Generated by Django 3.2.8 on 2021-10-15 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbank_api', '0002_account_open_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='joint',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
