# Generated by Django 3.2.8 on 2021-10-15 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbank_api', '0004_alter_account_open_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='open_date',
            field=models.DateField(auto_now=True),
        ),
    ]
