# Generated by Django 3.2.8 on 2021-10-23 21:11

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbank_api', '0006_alter_account_open_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=60)),
                ('birthday', models.DateField(default=datetime.date.today)),
                ('ssn', models.CharField(default='000000000', max_length=9, validators=[django.core.validators.MaxLengthValidator(9), django.core.validators.MinLengthValidator(9)])),
                ('address_one', models.CharField(max_length=60)),
                ('address_two', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=60)),
                ('state', models.CharField(choices=[('ALABAMA', 'AL'), ('ALASKA', 'AK'), ('AMERICAN SAMOA', 'AS'), ('ARIZONA', 'AZ'), ('ARKANSAS', 'AR'), ('CALIFORNIA', 'CA'), ('COLORADO', 'CO'), ('CONNECTICUT', 'CT'), ('DELAWARE', 'DE'), ('DISTRICT OF COLUMBIA', 'DC'), ('FLORIDA', 'FL'), ('GEORGIA', 'GA'), ('GUAM', 'GU'), ('HAWAII', 'HI'), ('IDAHO', 'ID'), ('ILLINOIS', 'IL'), ('INDIANA', 'IN'), ('IOWA', 'IA'), ('KANSAS', 'KS'), ('KENTUCKY', 'KY'), ('LOUISIANA', 'LA'), ('MAINE', 'ME'), ('MARYLAND', 'MD'), ('MASSACHUSETTS', 'MA'), ('MICHIGAN', 'MI'), ('MINNESOTA', 'MN'), ('MISSISSIPPI', 'MS'), ('MISSOURI', 'MO'), ('MONTANA', 'MT'), ('NEBRASKA', 'NE'), ('NEVADA', 'NV'), ('NEW HAMPSHIRE', 'NH'), ('NEW JERSEY', 'NJ'), ('NEW MEXICO', 'NM'), ('NEW YORK', 'NY'), ('NORTH CAROLINA', 'NC'), ('NORTH DAKOTA', 'ND'), ('NORTHERN MARIANA IS', 'MP'), ('OHIO', 'OH'), ('OKLAHOMA', 'OK'), ('OREGON', 'OR'), ('PENNSYLVANIA', 'PA'), ('PUERTO RICO', 'PR'), ('RHODE ISLAND', 'RI'), ('SOUTH CAROLINA', 'SC'), ('SOUTH DAKOTA', 'SD'), ('TENNESSEE', 'TN'), ('TEXAS', 'TX'), ('UTAH', 'UT'), ('VERMONT', 'VT'), ('VIRGINIA', 'VA'), ('VIRGIN ISLANDS', 'VI'), ('WASHINGTON', 'WA'), ('WEST VIRGINIA', 'WV'), ('WISCONSIN', 'WI'), ('WYOMING', 'WY')], max_length=30)),
                ('zip_code', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='member_id',
            field=models.ForeignKey(default='0000000000', on_delete=django.db.models.deletion.CASCADE, to='rbank_api.member'),
        ),
    ]
