# Generated by Django 3.2.8 on 2021-10-23 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbank_api', '0007_auto_20211023_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='address_two',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
