# Generated by Django 3.2.8 on 2021-10-23 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbank_api', '0008_alter_member_address_two'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='open_date',
            new_name='close_date',
        ),
        migrations.RemoveField(
            model_name='account',
            name='joint',
        ),
    ]
