# Generated by Django 3.2.8 on 2021-10-23 21:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbank_api', '0009_auto_20211023_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='owner',
        ),
        migrations.AddField(
            model_name='account',
            name='activity_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='account',
            name='open_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
