# Generated by Django 3.2.8 on 2021-10-23 22:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbank_api', '0011_alter_account_close_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_date', models.DateField(default=datetime.date.today)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=30)),
                ('close_date', models.DateField(blank=True)),
                ('share_type', models.CharField(choices=[('001', 'Checking'), ('002', 'Savings')], max_length=30)),
                ('acct_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbank_api.account')),
            ],
        ),
    ]
