# Generated by Django 3.2.8 on 2021-10-23 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbank_api', '0012_share'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='close_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
