# Generated by Django 3.2.8 on 2021-10-23 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbank_api', '0013_alter_share_close_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originator', models.CharField(max_length=80)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=30)),
                ('share_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbank_api.share')),
            ],
        ),
    ]
