# Generated by Django 3.2.8 on 2021-10-23 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbank_api', '0014_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('C', 'Credit'), ('D', 'Debit'), ('T', 'Transfer')], default='C', max_length=30),
            preserve_default=False,
        ),
    ]
